{% set version = '2.7.13' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dataretrieval
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dataRetrieval_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dataRetrieval/dataRetrieval_{{ version }}.tar.gz
  sha256: 3db2e87ae4b02fb38f591c1ca10cddc775c2f1d1d21a1715c5424b50141ed670

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-curl
    - r-httr >=1.0.0
    - r-jsonlite
    - r-lubridate >=1.5.0
    - r-readr >=1.4.0
    - r-xml2

  run:
    - r-base
    - r-curl
    - r-httr >=1.0.0
    - r-jsonlite
    - r-lubridate >=1.5.0
    - r-readr >=1.4.0
    - r-xml2

test:
  commands:
    - $R -e "library('dataRetrieval')"           # [not win]
    - "\"%R%\" -e \"library('dataRetrieval')\""  # [win]

about:
  home: https://code.usgs.gov/water/dataRetrieval
  license: CC0-1.0
  summary: Collection of functions to help retrieve U.S. Geological Survey and U.S. Environmental
    Protection Agency water quality and hydrology data from web services. Data are discovered
    from National Water Information System <https://waterservices.usgs.gov/> and <https://waterdata.usgs.gov/nwis>.
    Water quality data are obtained from the Water Quality Portal <https://www.waterqualitydata.us/>.
  license_family: CC
  license_file:
    - LICENSE.md

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# The original CRAN metadata for this package was:

# Package: dataRetrieval
# Type: Package
# Title: Retrieval Functions for USGS and EPA Hydrology and Water Quality Data
# Version: 2.7.13
# Authors@R: c( person("Laura", "DeCicco", role = c("aut","cre"), email = "ldecicco@usgs.gov", comment=c(ORCID="0000-0002-3915-9487")), person("Robert", "Hirsch", role = c("aut"), comment=c(ORCID="0000-0002-4534-075X")), person("David","Lorenz", role=c("aut")), person("Jordan", "Read", role = c("ctb")), person("Jordan", "Walker", role = c("ctb")), person("Lindsay","Carr", role=c("ctb")), person("David","Watkins", role=c("aut"), email = "wwatkins@usgs.gov", comment=c(ORCID="0000-0002-7544-0700")), person("David", "Blodgett", role="ctb"), person("Mike", "Johnson", role=c("aut"), email = "mikecp11@gmail.com", comment=c(ORCID="0000-0002-5288-8350")), person("Aliesha", "Krall", role="ctb", email = "akrall@usgs.gov", comment=c(ORCID="0000-0003-2521-5043")))
# Description: Collection of functions to help retrieve U.S. Geological Survey and U.S. Environmental Protection Agency water quality and hydrology data from web services. Data are discovered from National Water Information System <https://waterservices.usgs.gov/> and <https://waterdata.usgs.gov/nwis>. Water quality data are obtained from the Water Quality Portal <https://www.waterqualitydata.us/>.
# License: CC0
# Copyright: This software is in the public domain because it contains materials that originally came from the United States Geological Survey, an agency of the United States Department of Interior.
# Depends: R (>= 3.5.0)
# Imports: httr (>= 1.0.0), curl, lubridate (>= 1.5.0), stats, utils, xml2, readr (>= 1.4.0), jsonlite
# Suggests: covr, dplyr, ggplot2, DT, gridExtra, knitr, rmarkdown, sf, testthat
# Encoding: UTF-8
# BuildVignettes: true
# VignetteBuilder: knitr
# BugReports: https://github.com/DOI-USGS/dataRetrieval/issues
# URL: https://code.usgs.gov/water/dataRetrieval
# RoxygenNote: 7.2.3
# NeedsCompilation: no
# Packaged: 2023-07-20 20:33:39 UTC; ldecicco
# Author: Laura DeCicco [aut, cre] (<https://orcid.org/0000-0002-3915-9487>), Robert Hirsch [aut] (<https://orcid.org/0000-0002-4534-075X>), David Lorenz [aut], Jordan Read [ctb], Jordan Walker [ctb], Lindsay Carr [ctb], David Watkins [aut] (<https://orcid.org/0000-0002-7544-0700>), David Blodgett [ctb], Mike Johnson [aut] (<https://orcid.org/0000-0002-5288-8350>), Aliesha Krall [ctb] (<https://orcid.org/0000-0003-2521-5043>)
# Maintainer: Laura DeCicco <ldecicco@usgs.gov>
# Repository: CRAN
# Date/Publication: 2023-07-20 21:00:06 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
